---
abstract: 'Read and write CPAN index files'
author:
  - 'Peter Shangov <pshangov@yahoo.com>'
build_requires:
  File::Find: 0
  Test::More: 0
  Test::Most: 0
  Test::XML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Index-API
requires:
  Carp: 0
  Class::Load: 0
  Compress::Zlib: 0
  File::Basename: 0
  File::Slurp: 0
  File::Temp: 0
  LWP::Simple: 0
  List::Util: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::ClassAttribute: 0
  Path::Class: 0
  Scalar::Util: 0
  Symbol: 0
  Text::Template: 0
  URI: 0
  URI::file: 0
  XML::Twig: 0
  namespace::autoclean: 0
  namespace::clean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Index-API
version: 0.007
